name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm ci

      - name: NPM Lint
        run: npm run lint